congfig/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from home.views import home
from contact.views import contact

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('contact/', include('contact.urls')),
    path('product/', include('product.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path

from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.contact, name='contact'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('products/', views.product_list, name='product_list'),
    path('<int:pk>', views.product, name='product'),
]

contact/models.py
from django.db import models

# Create your models here.

product/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    description = models.TextField(default="", blank=True)
    stock_count = models.IntegerField(help_text="How many items are currently in stock.")

    def __str__(self):
        return self.name


class Product_image(models.Model):
    image = models.ImageField()
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name="images")

    def __str__(self):
        return str(self.image)

contact/views.py
from django.shortcuts import render

def contact(request):
    return render(request, 'contact/contact.html')

home/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home/home.html')

product/views.py
from django.shortcuts import render
from product.models import Product

def product(request, pk):
    item = Product.objects.get(pk=pk)
    return render(request, 'product/product.html', {'product': item})

def product_list(request):
    products = Product.objects.all()
    return render(request, 'product/product_list.html', {'products': products})

contact/templates/contact/contact.html
{% extends 'base.html' %}

{% block title %}contact{% endblock %}

{% block content %}
    <h1>Contact</h1>
{% endblock %}

<p>Nie zobaczysz mnie</p>

home/templates/home/home.html
{%  extends 'base.html' %}

{% block title %}home{% endblock %}

{% block content %}
    <h1>Welcome home!☺</h1>
{% endblock %}

product/templates/product/product.html
{% extends 'base.html' %}

{% block title %}{{ product.name}}{% endblock %}

{% block content %}
    <a href="{% url 'product:product_list' %}" class="btn btn-primary">Back</a>
    <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="/media/{{ product.images.first }}" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{ product }}</h5>
                    <p class="card-text">{{ product.description }}</p>
                    <p class="card-text"><small class="text-muted">Price: {{ product.price }}</small></p>
                    <p class="card-text"><small class="text-muted">Stock Count: {{ product.stock_count }}</small></p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

product/templates/product/product_list.html
{% extends 'base.html' %}

{% block title %}products{% endblock %}

{% block content %}
    <h1>Products:</h1>
    <div class="card-group">
        {% for product in products %}
            <div class="card" style="width: 18rem;">
                <img src="/media/{{ product.images.first }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">{{ product.description }}</p>
                    <a href="{% url 'product:product' pk=product.pk %}" class="btn btn-primary">Product detail</a>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Alegrosz - {% block title %}{% endblock %} </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}" async defer></script>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="{% static 'Zdjęcia/logo.svg' %}" alt="" width="30" height="24"
                 class="d-inline-block align-text-top">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contact:contact' %}">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'product:product_list' %}">Products</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container mt-5">
    <div class="row">
        <div class="col">
            {% block content %}

            {% endblock %}
        </div>
    </div>
</div>


</body>
</html>